/*

This data was generated for academic purposes and should not be used commercially.
Acknowledgements
Data Source: The Meal DB 
API Link: https://www.themealdb.com/api/json/v1/1/random.php
*/

let Menu = [
  {
    idMeal: "52921",
    strMeal: "Provençal Omelette Cake",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "French",
    strInstructions:
      "Break the eggs into two bowls, five in each. Whisk lightly and season with salt and pepper. Heat the oil in a pan, add the courgettes and spring onions, then fry gently for about 10 mins until softened. Cool, then stir into one bowl of eggs with a little salt and pepper. Add the roasted peppers to the other bowl of eggs with the garlic, chilli, salt and pepper.\r\nHeat a little oil in a 20-23cm frying pan, preferably non-stick. Pour the eggs with courgette into a measuring jug, then pourabout one-third of the mixture into the pan, swirling it to cover the base of the pan. Cook until the egg is set and lightly browned underneath, then cover the pan with a plate and invert the omelette onto it. Slide it back into the pan to cook the other side. Repeat with the remaining mix to make two more omelettes, adding a little oil to the pan each time. Stack the omelettes onto a plate. Make three omelettes in the same way with the red pepper mixture, then stack them on a separate plate.\r\nNow make the filling. Beat the cheese to soften it, then beat in the milk to make a spreadable consistency. Stir in the herbs, salt and pepper. Line a deep, 20-23cm round cake tin with cling film (use a tin the same size as the frying pan). Select the best red pepper omelette and place in the tin, prettiest side down. Spread with a thin layer of cheese filling, then cover with a courgette omelette. Repeat, alternating the layers, until all the omelettes and filling are in the tin, finishing with an omelette. Flip the cling film over the omelette, then chill for up to 24 hrs.\r\nTo serve, invert the omelette cake onto a serving plate and peel off the cling film. Pile rocket on the top and scatter over the cheese, a drizzle of olive oil and a little freshly ground black pepper. Serve cut into wedges.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/qwtrtp1511799242.jpg",
    strTags: "Egg",
    strYoutube: "https://www.youtube.com/watch?v=B7isFo2uP2k",
    strIngredient1: "Eggs",
    strIngredient2: "Olive Oil",
    strIngredient3: "Courgettes",
    strIngredient4: "Spring Onions",
    strIngredient5: "Red Pepper",
    strIngredient6: "Garlic Clove",
    strIngredient7: "Red Chilli",
    strIngredient8: "Cream Cheese",
    strIngredient9: "Milk",
    strIngredient10: "Chives",
    strIngredient11: "Basil",
    strIngredient12: "Rocket",
    strIngredient13: "Parmesan",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "10",
    strMeasure2: "1 tbs",
    strMeasure3: "2 finely chopped",
    strMeasure4: "3 finely chopped",
    strMeasure5: "4",
    strMeasure6: "1 clove peeled crushed",
    strMeasure7: "1",
    strMeasure8: "300g",
    strMeasure9: "6 tblsp",
    strMeasure10: "4 tbs",
    strMeasure11: "2 tbs",
    strMeasure12: "to serve",
    strMeasure13: "to serve",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "https://www.bbcgoodfood.com/recipes/6428/provenal-omelette-cake",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "17.49",
  },
  {
    idMeal: "52946",
    strMeal: "Kung Po Prawns",
    strDrinkAlternate: null,
    strCategory: "Seafood",
    strArea: "Chinese",
    strInstructions:
      "Mix the cornflour and 1 tbsp soy sauce, toss in the prawns and set aside for 10 mins. Stir the vinegar, remaining soy sauce, tomato purée, sugar and 2 tbsp water together to make a sauce.\r\n\r\nWhen you’re ready to cook, heat a large frying pan or wok until very hot, then add 1 tbsp oil. Fry the prawns until they are golden in places and have opened out– then tip them out of the pan.\r\n\r\nHeat the remaining oil and add the peanuts, chillies and water chestnuts. Stir-fry for 2 mins or until the peanuts start to colour, then add the ginger and garlic and fry for 1 more min. Tip in the prawns and sauce and simmer for 2 mins until thickened slightly. Serve with rice.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1525873040.jpg",
    strTags: "BBQ",
    strYoutube: "https://www.youtube.com/watch?v=ysiuZm9FIxs",
    strIngredient1: "Prawns",
    strIngredient2: "Soy Sauce",
    strIngredient3: "Tomato Puree",
    strIngredient4: "Corn Flour",
    strIngredient5: "Caster Sugar",
    strIngredient6: "Sunflower Oil",
    strIngredient7: "Peanuts",
    strIngredient8: "Chilli",
    strIngredient9: "Brown Sugar",
    strIngredient10: "Garlic Clove",
    strIngredient11: "Water Chestnut",
    strIngredient12: "Ginger",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "400g",
    strMeasure2: "2 tbs",
    strMeasure3: "1 tsp ",
    strMeasure4: "1 tsp ",
    strMeasure5: "1 tsp ",
    strMeasure6: "1 tsp ",
    strMeasure7: "85g",
    strMeasure8: "3 Large",
    strMeasure9: "1 tbs",
    strMeasure10: "6 cloves",
    strMeasure11: "450g",
    strMeasure12: "to taste",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/1415664/kung-po-prawns",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: 15.49,
  },

  {
    idMeal: "52952",
    strMeal: "Beef Lo Mein",
    strDrinkAlternate: null,
    strCategory: "Beef",
    strArea: "Chinese",
    strInstructions:
      "STEP 1 - MARINATING THE BEEF\r\nIn a bowl, add the beef, salt, 1 pinch white pepper, 1 Teaspoon sesame seed oil, 1/2 egg, corn starch,1 Tablespoon of oil and mix together.\r\nSTEP 2 - BOILING THE THE NOODLES\r\nIn a 6 qt pot add your noodles to boiling water until the noodles are submerged and boil on high heat for 10 seconds. After your noodles is done boiling strain and cool with cold water.\r\nSTEP 3 - STIR FRY\r\nAdd 2 Tablespoons of oil, beef and cook on high heat untill beef is medium cooked.\r\nSet the cooked beef aside\r\nIn a wok add 2 Tablespoon of oil, onions, minced garlic, minced ginger, bean sprouts, mushrooms, peapods and 1.5 cups of water or until the vegetables are submerged in water.\r\nAdd the noodles to wok\r\nTo make the sauce, add oyster sauce, 1 pinch white pepper, 1 teaspoon sesame seed oil, sugar, and 1 Teaspoon of soy sauce.\r\nNext add the beef to wok and stir-fry",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=ZT9LSsNXXe0",
    strIngredient1: "Beef",
    strIngredient2: "Salt",
    strIngredient3: "Pepper",
    strIngredient4: "Sesame Seed Oil",
    strIngredient5: "Egg",
    strIngredient6: "Starch",
    strIngredient7: "Oil",
    strIngredient8: "Noodles",
    strIngredient9: "Onion",
    strIngredient10: "Minced Garlic",
    strIngredient11: "Ginger",
    strIngredient12: "Bean Sprouts",
    strIngredient13: "Mushrooms",
    strIngredient14: "Water",
    strIngredient15: "Oyster Sauce",
    strIngredient16: "Sugar",
    strIngredient17: "Soy Sauce",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1/2 lb",
    strMeasure2: "pinch",
    strMeasure3: "pinch",
    strMeasure4: "2 tsp",
    strMeasure5: "1/2 ",
    strMeasure6: "3 tbs",
    strMeasure7: "5 tbs",
    strMeasure8: "1/4 lb",
    strMeasure9: "1/2 cup ",
    strMeasure10: "1 tsp ",
    strMeasure11: "1 tsp ",
    strMeasure12: "1 cup ",
    strMeasure13: "1 cup ",
    strMeasure14: "1 cup ",
    strMeasure15: "1 tbs",
    strMeasure16: "1 tsp ",
    strMeasure17: "1 tsp ",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://sueandgambo.com/pages/beef-lo-mein",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "14.99",
  },
  {
    idMeal: "52867",
    strMeal: "Vegetarian Chilli",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "British",
    strInstructions:
      "Heat oven to 200C/180C fan/ gas 6. Cook the vegetables in a casserole dish for 15 mins. Tip in the beans and tomatoes, season, and cook for another 10-15 mins until piping hot. Heat the pouch in the microwave on High for 1 min and serve with the chilli.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/wqurxy1511453156.jpg",
    strTags: "Chilli",
    strYoutube: "https://www.youtube.com/watch?v=D0bFRVH_EqU",
    strIngredient1: "Roasted Vegetables",
    strIngredient2: "Kidney Beans",
    strIngredient3: "Chopped Tomatoes",
    strIngredient4: "Mixed Grain",
    strIngredient5: "",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "400g",
    strMeasure2: "1 can ",
    strMeasure3: "1 can ",
    strMeasure4: "1 Packet",
    strMeasure5: "",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/veggie-chilli",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "8.99",
  },

  {
    idMeal: "52780",
    strMeal: "Potato Gratin with Chicken",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Unknown",
    strInstructions:
      "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=p3u8eiy3yHI",
    strIngredient1: "Potatoes",
    strIngredient2: "Onions",
    strIngredient3: "Olive Oil",
    strIngredient4: "Chicken Stock",
    strIngredient5: "Creme Fraiche",
    strIngredient6: "Parmesan",
    strIngredient7: "Chicken Breasts",
    strIngredient8: "Bacon",
    strIngredient9: "Spinach",
    strIngredient10: "Peas",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "800g",
    strMeasure2: "3",
    strMeasure3: "2 tblsp",
    strMeasure4: "100ml",
    strMeasure5: "1 pot",
    strMeasure6: "Topping",
    strMeasure7: "4",
    strMeasure8: "4",
    strMeasure9: "Topping",
    strMeasure10: "Topping",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: "https://www.instagram.com/p/BHxR7hYBJ6P",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "13.99",
  },
  {
    idMeal: "52868",
    strMeal: "Kidney Bean Curry",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "Indian",
    strInstructions:
      "Heat the oil in a large frying pan over a low-medium heat. Add the onion and a pinch of salt and cook slowly, stirring occasionally, until softened and just starting to colour. Add the garlic, ginger and coriander stalks and cook for a further 2 mins, until fragrant.\r\n\r\nAdd the spices to the pan and cook for another 1 min, by which point everything should smell aromatic. Tip in the chopped tomatoes and kidney beans in their water, then bring to the boil.\r\n\r\nTurn down the heat and simmer for 15 mins until the curry is nice and thick. Season to taste, then serve with the basmati rice and the coriander leaves.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
    strTags: "Curry",
    strYoutube: "https://www.youtube.com/watch?v=Tp_PMWvIKzo",
    strIngredient1: "Vegetable Oil",
    strIngredient2: "Onion",
    strIngredient3: "Garlic",
    strIngredient4: "Ginger",
    strIngredient5: "Coriander",
    strIngredient6: "Cumin",
    strIngredient7: "Paprika",
    strIngredient8: "Garam Masala",
    strIngredient9: "Chopped Tomatoes",
    strIngredient10: "Kidney Beans",
    strIngredient11: "Basmati Rice",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 tbls",
    strMeasure2: "1 finely chopped ",
    strMeasure3: "2 cloves chopped",
    strMeasure4: "1 part ",
    strMeasure5: "1 Packet",
    strMeasure6: "1 tsp ",
    strMeasure7: "1 tsp ",
    strMeasure8: "2 tsp",
    strMeasure9: "400g",
    strMeasure10: "400g",
    strMeasure11: "to serve",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "9.99",
  },
  {
    idMeal: "52839",
    strMeal: "Chilli prawn linguine",
    strDrinkAlternate: null,
    strCategory: "Pasta",
    strArea: "Italian",
    strInstructions:
      "Mix the dressing ingredients in a small bowl and season with salt and pepper. Set aside.\r\n\r\nCook the pasta according to the packet instructions. Add the sugar snap peas for the last minute or so of cooking time.\r\n\r\nMeanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown. Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink.\r\n\r\nAdd the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften. Drain the pasta and sugar snaps well, then toss into the prawn mixture. Tear in the basil leaves, stir, and season with salt and pepper.\r\n\r\nServe with salad leaves drizzled with the lime dressing, and warm crusty bread.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=SC17Mc70Db0",
    strIngredient1: "Linguine Pasta",
    strIngredient2: "Sugar Snap Peas",
    strIngredient3: "Olive Oil",
    strIngredient4: "Garlic Clove",
    strIngredient5: "Red Chilli",
    strIngredient6: "King Prawns",
    strIngredient7: "Cherry Tomatoes",
    strIngredient8: "Basil Leaves",
    strIngredient9: "Lettuce",
    strIngredient10: "Bread",
    strIngredient11: "Fromage Frais",
    strIngredient12: "Lime",
    strIngredient13: "Caster Sugar",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "280g",
    strMeasure2: "200g",
    strMeasure3: "2 tblsp ",
    strMeasure4: "2 cloves chopped",
    strMeasure5: "1 large",
    strMeasure6: "24 Skinned",
    strMeasure7: "12",
    strMeasure8: "Handful",
    strMeasure9: "Leaves",
    strMeasure10: "to serve",
    strMeasure11: "2 tbsp",
    strMeasure12: "Grated Zest of 2",
    strMeasure13: "2 tsp",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "21.99",
  },
  {
    idMeal: "52885",
    strMeal: " Bubble & Squeak",
    strDrinkAlternate: null,
    strCategory: "Pork",
    strArea: "British",
    strInstructions:
      "Melt the fat in a non-stick pan, allow it to get nice and hot, then add the bacon. As it begins to brown, add the onion and garlic. Next, add the sliced sprouts or cabbage and let it colour slightly. All this will take 5-6 mins.\r\nNext, add the potato. Work everything together in the pan and push it down so that the mixture covers the base of the pan – allow the mixture to catch slightly on the base of the pan before turning it over and doing the same again. It’s the bits of potato that catch in the pan that define the term ‘bubble and squeak’, so be brave and let the mixture colour. Cut into wedges and serve.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xusqvw1511638311.jpg",
    strTags: "SideDish,Speciality",
    strYoutube: "https://www.youtube.com/watch?v=etbJ9ssgsWY",
    strIngredient1: "Butter",
    strIngredient2: "Bacon",
    strIngredient3: "Onion",
    strIngredient4: "Garlic Clove",
    strIngredient5: "Brussels Sprouts",
    strIngredient6: "Potatoes",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 tbs",
    strMeasure2: "4",
    strMeasure3: "1 finely sliced",
    strMeasure4: "1 chopped",
    strMeasure5: "20",
    strMeasure6: "400g",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/164622/bubble-and-squeak",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "16.99",
  },
  {
    idMeal: "53007",
    strMeal: "Honey Yogurt Cheesecake",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "Greek",
    strInstructions:
      "Heat oven to 160C/140C fan/gas 3. Crush the biscuits and most of the almonds inside a plastic food bag using a rolling pin. Mix with the butter, then press into the bottom of a deep, oval, 23cm dish (or something similar in size – a roasting tin, baking dish or cake tin will work). Bake for 10 mins until crisp.\r\n\r\nStir or mash together the yogurt and mascarpone, then whisk in the eggs, one at a time. Stir in the lemon and orange zests, then stir in most of the honey, reserving about 3 tbsp. Spread over the biscuit base, cover loosely with foil and cook for 1 hr. Remove the foil and cook for 15 mins more until lightly golden and the top is firm with just the slightest wobble in the middle. Leave to cool. Can be kept in the fridge for up to 2 days.\r\n\r\nTo serve, scatter with almonds, drizzle over the remaining honey, and hand around fresh fruit to go with it.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/y2irzl1585563479.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=JE8crtueXs8",
    strIngredient1: "Digestive Biscuits",
    strIngredient2: "Almonds",
    strIngredient3: "Butter",
    strIngredient4: "Greek Yogurt",
    strIngredient5: "Mascarpone",
    strIngredient6: "Eggs",
    strIngredient7: "Lemon",
    strIngredient8: "Orange",
    strIngredient9: "Honey",
    strIngredient10: "Fruit Mix",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "100g ",
    strMeasure2: "85g",
    strMeasure3: "85g",
    strMeasure4: "250ml",
    strMeasure5: "750g",
    strMeasure6: "2",
    strMeasure7: "Zest of 1",
    strMeasure8: "Zest of 1",
    strMeasure9: "250ml",
    strMeasure10: "To serve",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/honey-yogurt-cheesecake",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "8.99",
  },
  {
    idMeal: "52793",
    strMeal: "Sticky Toffee Pudding Ultimate",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "Stone and chop the dates quite small, put them in a bowl, then pour the boiling water over. Leave for about 30 mins until cool and well-soaked, then mash a bit with a fork. Stir in the vanilla extract. Butter and flour seven mini pudding tins (each about 200ml/7fl oz) and sit them on a baking sheet. Heat oven to 180C/fan 160C/gas 4.\r\nWhile the dates are soaking, make the puddings. Mix the flour and bicarbonate of soda together and beat the eggs in a separate bowl. Beat the butter and sugar together in a large bowl for a few mins until slightly creamy (the mixture will be grainy from the sugar). Add the eggs a little at a time, beating well between additions. Beat in the black treacle then, using a large metal spoon, gently fold in one-third of the flour, then half the milk, being careful not to overbeat. Repeat until all the flour and milk is used. Stir the soaked dates into the pudding batter. The mix may look a little curdled at this point and will be like a soft, thick batter. Spoon it evenly between the tins and bake for 20-25 mins, until risen and firm.\r\nMeanwhile, put the sugar and butter for the sauce in a medium saucepan with half the cream. Bring to the boil over a medium heat, stirring all the time, until the sugar has completely dissolved. Stir in the black treacle, turn up the heat slightly and let the mixture bubble away for 2-3 mins until it is a rich toffee colour, stirring occasionally to make sure it doesn’t burn. Take the pan off the heat and beat in the rest of the cream.\r\nRemove the puddings from the oven. Leave in the tins for a few mins, then loosen them well from the sides of the tins with a small palette knife before turning them out. You can serve them now with the sauce drizzled over, but they’ll be even stickier if left for a day or two coated in the sauce. To do this, pour about half the sauce into one or two ovenproof serving dishes. Sit the upturned puddings on the sauce, then pour the rest of the sauce over them. Cover with a loose tent of foil so that the sauce doesn’t smudge (no need to chill).\r\nWhen ready to serve, heat oven to 180C/fan 160C/gas 4. Warm the puddings through, still covered, for 15-20 mins or until the sauce is bubbling. Serve them on their own, or with cream or custard.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xrptpq1483909204.jpg",
    strTags: "Pudding,Desert,Cake,Dairy",
    strYoutube: "https://www.youtube.com/watch?v=hKq6RbxJHBo",
    strIngredient1: "Medjool dates",
    strIngredient2: "water",
    strIngredient3: "vanilla extract",
    strIngredient4: "self-raising flour",
    strIngredient5: "bicarbonate of soda",
    strIngredient6: "eggs",
    strIngredient7: "butter",
    strIngredient8: "demerara sugar",
    strIngredient9: "black treacle",
    strIngredient10: "milk",
    strIngredient11: "ice cream",
    strIngredient12: "muscovado sugar",
    strIngredient13: "butter",
    strIngredient14: "double cream",
    strIngredient15: "black treacle",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "225g",
    strMeasure2: "175ml Boiling",
    strMeasure3: "1 tsp",
    strMeasure4: "175g",
    strMeasure5: "1 tsp",
    strMeasure6: "2",
    strMeasure7: "85g",
    strMeasure8: "140g",
    strMeasure9: "2 tbsp",
    strMeasure10: "100ml",
    strMeasure11: "1 scoop",
    strMeasure12: "175g",
    strMeasure13: "50g",
    strMeasure14: "225ml",
    strMeasure15: "1 tbsp",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.youtube.com/watch?v=Wytv3bjqJII",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    price: "8.99",
  },
];

export default Menu;
